### ISSUE TITLE
Question about the repo related paper

### ISSUE THREAD

**Issue by ChampionNan** [nicholasngai/distributed-sgx-sort#1]
Hi, is this the repo about the paper: Distributed & Scalable Oblivious Sorting and Shuffling[https://eprint.iacr.org/2024/627.pdf]

**Comment by ChampionNan** [comment]
Hi, is this the repo about the paper: Distributed & Scalable Oblivious Sorting and Shuffling[https://eprint.iacr.org/2024/627.pdf]

**Comment by nicholasngai** [comment]
Hi! Yes!
