### ISSUE TITLE
oe_create_parallel_enclave

### ISSUE THREAD

**Issue by ChampionNan** [nicholasngai/distributed-sgx-sort#2]
Hi, 

Sorry to bother again. I just wondered about the api `oe_create_parallel_enclave` used in your code, which I couldn't find it in the official document. Is a new implemented api? Where can I find it? 

Thanks!

**Comment by nicholasngai** [comment]
Ahhh, so `oe_create_<name>_enclave` is the function that is generated for an enclave named `<name>`! In this case, we have `parallel.edl`, so the enclave’s name is `parallel`, and the generated function name is `oe_create_parallel_enclave`!
